### ISSUE TITLE
trying to figure out this bug coming from provider.py

### ISSUE THREAD

**Issue by chiggimps** [0xOmarA/RadixLib#13]
Any ideas? I've updated to the latest.

```
transactions_list = getTransactionHistory(wallet_addresses)
  File "/home/ubuntu/NattyRadishesReservationTracker/main.py", line 495, in getTransactionHistory
    query_response: Dict[str, Any] = provider.get_account_transactions(
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/radixlib/provider.py", line 261, in get_account_transactions
    return self.__dispatch(
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/radixlib/provider.py", line 95, in __dispatch
    response: requests.Response = requests.request(
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/requests/sessions.py", line 687, in send
    r.content
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/requests/models.py", line 838, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/requests/models.py", line 763, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
Traceback (most recent call last):
  File "/home/ubuntu/NattyRadishesReservationTracker/env/lib/python3.9/site-packages/urllib3/response.py", line 697, in _update_chunk_length
    self.chunk_left = int(line, 16)
ValueError: invalid literal for int() with base 16: b''
```

**Comment by chiggimps** [comment]
Not getting this anymore. Could have been timeouts on the main gateway
